.TH Hangman 1 "March 2014" "Hangman 1.15" "Hangman User Manual"
.SH NAME
hangman \- Starts a game of Hangman
.SH SYNOPSIS
\fBhangman\fR [\fIphrase\fR]
.SH DESCRIPTION
Just a simple game of hangman. [\fIphrase\fR], if specified, sets the secret phrase. Otherwise, a random phrase from the default list (see phraseGen.c) will be chosen
.SH AUTHOR
Braden Best <\fIbradentbest@gmail.com\fR>
